# Generated by Django 4.2.30 on 2026-05-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkMusicEvent',
            new_name='LinkEventMusic',
        ),
    ]
