# Generated by Django 4.2.30 on 2026-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0002_user_is_manager'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('event_name', 'youtube_music'), name='unique_event_youtube_music_combination'),
        ),
        migrations.AddConstraint(
            model_name='youtubemusic',
            constraint=models.UniqueConstraint(fields=('name', 'url'), name='unique_name_url_combination'),
        ),
    ]
