# Generated by Django 4.2.30 on 2026-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0002_rename_linkmusicevent_linkeventmusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
