# Generated by Django 4.2.30 on 2026-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0003_plan_end_date_plan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('experimentacao', 'Experimentação')], default='mensal', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='plan',
            table=None,
        ),
    ]
