# Generated by Django 4.2.30 on 2026-05-09 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0003_event_unique_event_youtube_music_combination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMusicEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'event',
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_youtube_music_combination',
        ),
        migrations.RemoveField(
            model_name='event',
            name='youtube_music',
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AddField(
            model_name='linkmusicevent',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sonoraAPI.event'),
        ),
        migrations.AddField(
            model_name='linkmusicevent',
            name='music_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sonoraAPI.youtubemusic'),
        ),
        migrations.AddConstraint(
            model_name='linkmusicevent',
            constraint=models.UniqueConstraint(fields=('event_id', 'music_id'), name='unique_event_music_combination'),
        ),
    ]
