# Generated by Django 4.2.30 on 2026-05-14 00:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0004_alter_plan_end_date_alter_plan_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonoraAPI.event')),
            ],
            options={
                'db_table': 'music_order',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='youtubemusic',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='youtubemusic',
            name='singer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='LinkEventMusic',
        ),
        migrations.AddField(
            model_name='musicorder',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonoraAPI.youtubemusic'),
        ),
        migrations.AddConstraint(
            model_name='musicorder',
            constraint=models.UniqueConstraint(fields=('event_id', 'music_id'), name='unique_event_music_combination'),
        ),
    ]
