# Generated by Django 4.2.30 on 2026-05-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0004_linkmusicevent_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='linkmusicevent',
            table='link_event_music',
        ),
    ]
