# Generated by Django 4.2.30 on 2026-05-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0005_musicorder_youtubemusic_duration_youtubemusic_singer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='musicorder',
            name='unique_event_music_combination',
        ),
        migrations.RenameField(
            model_name='musicorder',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='musicorder',
            old_name='music_id',
            new_name='music',
        ),
        migrations.AddConstraint(
            model_name='musicorder',
            constraint=models.UniqueConstraint(fields=('event', 'music'), name='unique_event_music_combination'),
        ),
    ]
