# Generated by Django 4.2.30 on 2026-05-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0006_remove_musicorder_unique_event_music_combination_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='musicorder',
            name='unique_event_music_combination',
        ),
        migrations.AddConstraint(
            model_name='musicorder',
            constraint=models.UniqueConstraint(fields=('event', 'music', 'order'), name='unique_event_music_and_order_combination'),
        ),
    ]
