# Generated by Django 5.2.14 on 2026-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0007_remove_musicorder_unique_event_music_combination_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='musicorder',
            name='unique_event_music_and_order_combination',
        ),
        migrations.AddConstraint(
            model_name='musicorder',
            constraint=models.UniqueConstraint(fields=('event', 'music'), name='unique_event_music_combination'),
        ),
        migrations.AddConstraint(
            model_name='musicorder',
            constraint=models.UniqueConstraint(fields=('music', 'order'), name='unique_music_order_combination'),
        ),
    ]
