# Generated by Django 5.2.14 on 2026-05-28 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonoraAPI', '0008_remove_musicorder_unique_event_music_and_order_combination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'folders',
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='musicorder',
            name='unique_music_order_combination',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='eceveve', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicorder',
            name='category',
            field=models.CharField(choices=[('interactive', 'Reações'), ('background', 'Fundo')], default='interactive', max_length=20),
        ),
        migrations.AddField(
            model_name='musicorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musicorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('rejected', 'Rejeitada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='youtubemusic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='musics/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubemusic',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='sonoraAPI.event'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='sonoraAPI.folder'),
        ),
        migrations.AddField(
            model_name='musicorder',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_orders', to='sonoraAPI.folder'),
        ),
        migrations.AddConstraint(
            model_name='musicorder',
            constraint=models.UniqueConstraint(fields=('event', 'order'), name='unique_event_order_combination'),
        ),
    ]
